import fs from 'node:fs';

function replaceWithin(source, anchor, from, to, label) {
    const anchorIndex = source.indexOf(anchor);
    if (anchorIndex < 0) throw new Error('Missing v0.4.21 anchor: ' + label);
    const index = source.indexOf(from, anchorIndex);
    if (index < 0) {
        if (source.indexOf(to, anchorIndex) >= 0) return source;
        throw new Error('Missing v0.4.21 marker: ' + label);
    }
    return source.slice(0, index) + to + source.slice(index + from.length);
}

let schema = fs.readFileSync('v03/schema.js', 'utf8');
schema = replaceWithin(
    schema,
    'const relationshipHistory = Array.isArray(input.relationshipHistory)',
    "        reason: text(item?.reason, 800),\n        sourceMessageId: Number.isInteger(item?.sourceMessageId) ? item.sourceMessageId : null,",
    "        reason: text(item?.reason, 800),\n        axisEvidence: normalizeRelationshipAxisEvidence(item?.axisEvidence),\n        priority: normalizeRelationshipPriority(item?.priority),\n        verifiedSources: normalizeRelationshipVerifiedSources(item?.verifiedSources),\n        sourceMessageId: Number.isInteger(item?.sourceMessageId) ? item.sourceMessageId : null,",
    'relationshipHistory evidence metadata',
);
schema = replaceWithin(
    schema,
    'lastRelationshipChange: input.lastRelationshipChange ?',
    "            reason: text(input.lastRelationshipChange.reason, 800),\n            sourceMessageId: Number.isInteger(input.lastRelationshipChange.sourceMessageId) ? input.lastRelationshipChange.sourceMessageId : null,",
    "            reason: text(input.lastRelationshipChange.reason, 800),\n            axisEvidence: normalizeRelationshipAxisEvidence(input.lastRelationshipChange.axisEvidence),\n            priority: normalizeRelationshipPriority(input.lastRelationshipChange.priority),\n            verifiedSources: normalizeRelationshipVerifiedSources(input.lastRelationshipChange.verifiedSources),\n            sourceMessageId: Number.isInteger(input.lastRelationshipChange.sourceMessageId) ? input.lastRelationshipChange.sourceMessageId : null,",
    'lastRelationshipChange evidence metadata',
);
fs.writeFileSync('v03/schema.js', schema);

let dossier = fs.readFileSync('v03/dossier-view.js', 'utf8');
if (!dossier.includes('function relationshipHistoryRemarkHtml')) {
    const start = dossier.indexOf('function relationshipHistoryHtml(npc = {}) {');
    const end = dossier.indexOf('\n\nfunction relationshipDiagnosticsHtml', start);
    if (start < 0 || end < 0) throw new Error('Missing relationshipHistoryHtml replacement boundary');
    const replacement = [
        'function relationshipChangedAxes(event = {}) {',
        '    return RELATIONSHIP_AXES.filter(axis => Number(event?.delta?.[axis]) !== 0);',
        '}',
        '',
        'function relationshipExplanationKey(value) {',
        "    return String(value || '').replace(/\\s+/g, ' ').trim().toLocaleLowerCase();",
        '}',
        '',
        'function relationshipHistoryIdentityScore(history, candidate) {',
        '    let score = 0;',
        '    const historyMessage = Number.isInteger(history?.sourceMessageId) ? history.sourceMessageId : null;',
        '    const candidateMessage = Number.isInteger(candidate?.sourceMessageId) ? candidate.sourceMessageId : null;',
        '    if (historyMessage !== null && candidateMessage !== null) {',
        '        if (historyMessage !== candidateMessage) return -1;',
        '        score += 8;',
        '    }',
        '    const historyTurn = Number.isInteger(history?.turn) ? history.turn : null;',
        '    const candidateTurn = Number.isInteger(candidate?.turn) ? candidate.turn : null;',
        '    if (historyTurn !== null && candidateTurn !== null) {',
        '        if (historyTurn !== candidateTurn) return -1;',
        '        score += 4;',
        '    }',
        '    const historyAt = Number(history?.at) || 0;',
        '    const candidateAt = Number(candidate?.at) || 0;',
        '    if (historyAt && candidateAt && historyAt === candidateAt) score += 6;',
        '    if (!score) return -1;',
        "    const historyImpact = String(history?.impact || '').trim();",
        "    const candidateImpact = String(candidate?.impact || '').trim();",
        '    if (historyImpact && candidateImpact && historyImpact !== candidateImpact) return -1;',
        "    const historyEvidence = String(history?.evidence || '').replace(/\\s+/g, ' ').trim();",
        "    const candidateEvidence = String(candidate?.evidence || '').replace(/\\s+/g, ' ').trim();",
        '    if (historyEvidence && candidateEvidence && historyEvidence === candidateEvidence) score += 2;',
        '    return score;',
        '}',
        '',
        'function relationshipHistoryCandidateSupports(history, candidate, kind) {',
        '    const delta = kind === \'diagnostic\' ? candidate?.applied : candidate?.delta;',
        '    return relationshipChangedAxes(history).every(axis => {',
        '        const actual = Number(history?.delta?.[axis]) || 0;',
        '        const proposed = Number(delta?.[axis]) || 0;',
        '        return proposed !== 0 && Math.sign(proposed) === Math.sign(actual);',
        '    });',
        '}',
        '',
        'function relationshipHistoryRecoveryGroupKey(candidate) {',
        '    const message = Number.isInteger(candidate?.sourceMessageId) ? candidate.sourceMessageId : null;',
        '    const turn = Number.isInteger(candidate?.turn) ? candidate.turn : null;',
        '    const at = Number(candidate?.at) || 0;',
        "    if (message !== null) return 'm:' + message + '|t:' + (turn === null ? '?' : turn);",
        "    if (turn !== null) return 't:' + turn + '|a:' + (at || '?');",
        "    return at ? 'a:' + at : '';",
        '}',
        '',
        'function relationshipHistoryRecoveredAxisEvidence(npc, history) {',
        '    const changedAxes = relationshipChangedAxes(history);',
        '    if (!changedAxes.length) return {};',
        '    const candidates = [',
        "        ...(Array.isArray(npc?.relationshipEvidenceHistory) ? npc.relationshipEvidenceHistory : []).map(item => ({ kind: 'evidence', item })),",
        "        ...(Array.isArray(npc?.relationshipDiagnostics) ? npc.relationshipDiagnostics : []).map(item => ({ kind: 'diagnostic', item })),",
        '    ].map(entry => ({ ...entry, score: relationshipHistoryIdentityScore(history, entry.item) }))',
        '        .filter(entry => entry.score >= 0',
        '            && relationshipHistoryCandidateSupports(history, entry.item, entry.kind)',
        '            && changedAxes.some(axis => String(entry.item?.axisEvidence?.[axis]?.explanation || \'\').trim()));',
        '    if (!candidates.length) return {};',
        '    const strongest = Math.max(...candidates.map(entry => entry.score));',
        '    const top = candidates.filter(entry => entry.score === strongest);',
        '    const groups = new Map();',
        '    for (const entry of top) {',
        '        const key = relationshipHistoryRecoveryGroupKey(entry.item);',
        '        if (!key) continue;',
        '        if (!groups.has(key)) groups.set(key, []);',
        '        groups.get(key).push(entry.item);',
        '    }',
        '    if (groups.size !== 1) return {};',
        '    const members = [...groups.values()][0];',
        '    const out = {};',
        '    const ambiguous = new Set();',
        '    for (const candidate of members) {',
        '        for (const axis of changedAxes) {',
        "            const explanation = String(candidate?.axisEvidence?.[axis]?.explanation || '').replace(/\\s+/g, ' ').trim();",
        '            if (!explanation) continue;',
        '            if (!out[axis]) {',
        '                out[axis] = { explanation };',
        '                continue;',
        '            }',
        '            if (relationshipExplanationKey(out[axis].explanation) !== relationshipExplanationKey(explanation)) ambiguous.add(axis);',
        '        }',
        '    }',
        '    for (const axis of ambiguous) delete out[axis];',
        '    return out;',
        '}',
        '',
        'function relationshipHistoryAxisEvidence(npc, event) {',
        '    const changedAxes = relationshipChangedAxes(event);',
        '    const out = {};',
        '    for (const axis of changedAxes) {',
        "        const explanation = String(event?.axisEvidence?.[axis]?.explanation || '').replace(/\\s+/g, ' ').trim();",
        '        if (explanation) out[axis] = { explanation };',
        '    }',
        '    if (changedAxes.every(axis => out[axis])) return out;',
        '    const recovered = relationshipHistoryRecoveredAxisEvidence(npc, event);',
        '    for (const axis of changedAxes) if (!out[axis] && recovered[axis]) out[axis] = recovered[axis];',
        '    return out;',
        '}',
        '',
        'function relationshipHistoryRemarkHtml(npc, event) {',
        "    const reason = String(event?.reason || '').replace(/\\s+/g, ' ').trim();",
        "    if (reason) return '<p>' + escapeHtml(reason) + '</p>';",
        '    const evidence = relationshipHistoryAxisEvidence(npc, event);',
        '    const rows = [];',
        '    const rowByExplanation = new Map();',
        '    for (const axis of relationshipChangedAxes(event)) {',
        "        const explanation = String(evidence?.[axis]?.explanation || '').replace(/\\s+/g, ' ').trim();",
        '        if (!explanation) continue;',
        '        const key = relationshipExplanationKey(explanation);',
        '        const label = axis.charAt(0).toUpperCase() + axis.slice(1);',
        '        if (rowByExplanation.has(key)) {',
        '            rowByExplanation.get(key).labels.push(label);',
        '            continue;',
        '        }',
        '        const row = { labels: [label], explanation };',
        '        rowByExplanation.set(key, row);',
        '        rows.push(row);',
        '    }',
        "    if (!rows.length) return '<p class=\"npc-state-muted\">No explanation recorded.</p>';",
        "    return '<p>' + rows.map(row => '<b>' + escapeHtml(row.labels.join(' / ')) + ':</b> ' + escapeHtml(row.explanation)).join('<br>') + '</p>';",
        '}',
        '',
        'function relationshipHistoryHtml(npc = {}) {',
        '    const rows = Array.isArray(npc.relationshipHistory) ? npc.relationshipHistory.slice(-24).reverse() : [];',
        "    if (!rows.length) return '<p class=\"npc-state-muted\">No relationship change history yet.</p>';",
        "    return '<ol class=\"npc-state-v3-history-list\">' + rows.map((event, index) => {",
        '        const delta = Object.entries(event?.delta || {})',
        '            .filter(([, value]) => Number(value))',
        "            .map(([key, value]) => key + ' ' + (Number(value) > 0 ? '+' : '') + Number(value))",
        "            .join(', ');",
        "        const impact = escapeHtml(event?.impact || 'ordinary');",
        "        return '<li' + (index >= 8 ? ' hidden' : '') + '><div><b>' + impact + '</b><span>' + escapeHtml(delta || 'no score change') + '</span></div>' + relationshipHistoryRemarkHtml(npc, event) + '</li>';",
        "    }).join('') + '</ol>';",
        '}',
    ].join('\n');
    dossier = dossier.slice(0, start) + replacement + dossier.slice(end);
}
fs.writeFileSync('v03/dossier-view.js', dossier);

console.log('Applied NPC State 0.4.21 relationship history remarks persistence and recovery');
