import assert from 'node:assert/strict';
import fs from 'node:fs';
const read = path => fs.readFileSync(path, 'utf8');
const manifest = JSON.parse(read('manifest.json'));
const scanner = read('v03/scanner.js');
const injection = read('v03/injection.js');
const phase36 = read('beta/phase36-per-axis-relationship-grounding-0.4.19.mjs');
const verify36 = read('beta/verify-phase36-per-axis-relationship-grounding-0.4.19.mjs');
const workflow = read('.github/workflows/seed-beta.yml');
const patch = Number(String(manifest.version || '').split('.')[2]);
assert(String(manifest.version).startsWith('0.4.') && patch >= 19, 'Release source regressed below v0.4.19');
assert(phase36.includes('relationshipAxisGrounding'), 'Historical v0.4.19 per-axis transform source is missing');
assert(verify36.includes('another axis was weak'), 'Historical mixed-axis regression intent is not persisted');
assert(scanner.includes('relationshipAxisProvenance') && scanner.includes('relationshipEvidenceExcerptMatch'), 'Descendant runtime lacks v0.4.20 per-axis provenance');
assert(!scanner.includes('relationshipEvidenceGrounding('), 'Descendant runtime restored legacy semantic authorization');
assert(injection.includes('PER-AXIS RELATIONSHIP EVIDENCE'), 'Descendant foreground contract lacks per-axis evidence');
assert(workflow.includes('node beta/bump-0.4.19.mjs'), 'Workflow no longer preserves the v0.4.19 build step');
assert(workflow.includes('node beta/bump-0.4.20.mjs'), 'Workflow does not apply the v0.4.20 descendant');
assert(workflow.includes('Generated beta runtime already matches build output.'));
console.log('NPC State 0.4.19 release source parity verified for v0.4.20+ descendant');
